flask:
  build: flask/
  ports:
  -  "5000:5000"
  volumes:
  -  flask:/workspace
  links:
  -  db
db:
  build: postgres/
interlock:
  image: ehazlett/interlock
  ports:
  -  "80:8080"
  volumes:
  - /var/lib/boot2docker:/etc/docker
  